<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>gielinomics-ingest</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.0.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.1" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.11.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Gielinomics.Client/Gielinomics.Client.csproj" />
    <ProjectReference Include="../Gielinomics.Data/Gielinomics.Data.csproj" />
  </ItemGroup>

</Project>
