/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Searches items by name, membership and buy limit. */
        get: operations["SearchItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetches one item's reference metadata. */
        get: operations["GetItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetches this platform's retained price history for an item. */
        get: operations["GetItemPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Computes volatility, mean spread and liquidity over retained history. */
        get: operations["GetItemStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/movers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranks items by percentage price change over a window. */
        get: operations["GetMovers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/spreads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scans for flip margins, adjusted for Grand Exchange tax. */
        get: operations["GetSpreads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-feed last success and recent failure counts. */
        get: operations["GetIngestStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fraction of the expected windows actually retained. */
        get: operations["GetIngestCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the calling token's alert rules. */
        get: operations["ListAlerts"];
        put?: never;
        /** Creates an alert rule. The webhook host is validated on write. */
        post: operations["CreateAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolves an account by any name it has ever used. */
        get: operations["GetPlayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{name}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-skill history for a tracked account. */
        get: operations["GetPlayerHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{name}/gains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experience and levels gained over a period. */
        get: operations["GetPlayerGains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{name}/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts tracking an account. Authenticated: tracking adds polling load. */
        post: operations["TrackPlayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlertListResponse: {
            rules: components["schemas"]["AlertRule"][];
        };
        AlertRule: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            ownerId: number;
            kind: string;
            config: string;
            webhookUrl: string;
            enabled: boolean;
            /** Format: date-time */
            lastFired: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CoverageReport: {
            /** Format: int32 */
            stepSeconds: number;
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /** Format: int64 */
            expectedWindows: number;
            /** Format: int64 */
            presentWindows: number;
            /** Format: double */
            coverage: number;
        };
        CreateAlertRequest: {
            kind: string | null;
            config: components["schemas"]["JsonElement"];
            webhookUrl: string | null;
        };
        FeedStatus: {
            source: string;
            /** Format: date-time */
            lastSuccessAt: string | null;
            sinceLastSuccess: string | null;
            /** Format: int64 */
            runsLastDay: number;
            /** Format: int64 */
            failuresLastDay: number;
        };
        HealthResponse: {
            status: string;
        };
        IngestStatusResponse: {
            feeds: components["schemas"]["FeedStatus"][];
        };
        ItemDetail: {
            /** Format: int32 */
            id: number;
            name: string | null;
            examine: string | null;
            members: boolean | null;
            /** Format: int32 */
            buyLimit: number | null;
            /** Format: int64 */
            value: number | null;
            /** Format: int64 */
            lowAlch: number | null;
            /** Format: int64 */
            highAlch: number | null;
            icon: string | null;
            isStub: boolean;
            /** Format: date-time */
            firstSeen: string;
            /** Format: date-time */
            lastSeen: string;
        };
        ItemPriceSeries: {
            /** Format: int32 */
            itemId: number;
            /** Format: int32 */
            stepSeconds: number;
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            points: components["schemas"]["PricePoint"][];
        };
        ItemStats: {
            /** Format: int32 */
            itemId: number;
            /** Format: int32 */
            stepSeconds: number;
            /** Format: date-time */
            from: string;
            /** Format: int64 */
            samples: number;
            /** Format: double */
            meanHigh: number | null;
            /** Format: double */
            stdDevHigh: number | null;
            /** Format: double */
            volatility: number | null;
            /** Format: double */
            meanSpread: number | null;
            /** Format: int64 */
            highVolume: number;
            /** Format: int64 */
            lowVolume: number;
        };
        ItemSummary: {
            /** Format: int32 */
            id: number;
            name: string | null;
            members: boolean | null;
            /** Format: int32 */
            buyLimit: number | null;
            /** Format: int64 */
            highAlch: number | null;
            icon: string | null;
            isStub: boolean;
        };
        JsonElement: unknown;
        MarginCandidate: {
            /** Format: int32 */
            itemId: number;
            name: string | null;
            /** Format: int64 */
            buyPrice: number;
            /** Format: int64 */
            sellPrice: number;
            /** Format: int64 */
            tax: number;
            /** Format: int64 */
            netMargin: number;
            /** Format: int32 */
            buyLimit: number | null;
            /** Format: int64 */
            netMarginPerLimit: number;
            /** Format: int64 */
            highVolume: number;
            /** Format: int64 */
            lowVolume: number;
            /** Format: date-time */
            observedAt: string;
        };
        MarketMover: {
            /** Format: int32 */
            itemId: number;
            name: string | null;
            /** Format: double */
            startPrice: number;
            /** Format: double */
            endPrice: number;
            /** Format: double */
            changePercent: number;
            /** Format: int64 */
            volume: number;
        };
        MoversResponse: {
            window: string;
            /** Format: int32 */
            stepSeconds: number;
            movers: components["schemas"]["MarketMover"][];
        };
        PageOfItemSummary: {
            items: components["schemas"]["ItemSummary"][];
            nextCursor: string | null;
        };
        Player: {
            /** Format: int64 */
            id: number;
            displayName: string;
            normalisedName: string;
            accountType: string;
            tracked: boolean;
            /** Format: date-time */
            addedAt: string;
        };
        PlayerGainsResponse: {
            player: string;
            period: string;
            overall: components["schemas"]["SkillGain"];
            skills: components["schemas"]["SkillGain2"][];
        };
        PlayerHistoryResponse: {
            player: string;
            /** Format: int32 */
            mappingVersion: number;
            skillNames: string[];
            samples: components["schemas"]["SkillSample"][];
        };
        PlayerName: {
            name: string;
            /** Format: date-time */
            seenFrom: string;
            /** Format: date-time */
            seenTo: string | null;
        };
        PlayerResponse: {
            player: components["schemas"]["Player"];
            names: components["schemas"]["PlayerName"][];
        };
        PricePoint: {
            /** Format: date-time */
            bucketTs: string;
            /** Format: double */
            avgHigh: number | null;
            /** Format: double */
            avgLow: number | null;
            /** Format: int64 */
            highVolume: number;
            /** Format: int64 */
            lowVolume: number;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        };
        SkillGain: {
            /** Format: int16 */
            skill: number;
            name: string | null;
            /** Format: int64 */
            startXp: number | null;
            /** Format: int64 */
            endXp: number | null;
            /** Format: int64 */
            gainedXp: number;
            /** Format: int16 */
            startLevel: number | null;
            /** Format: int16 */
            endLevel: number | null;
            /** Format: int32 */
            gainedLevels: number;
        } | null;
        SkillGain2: {
            /** Format: int16 */
            skill: number;
            name: string | null;
            /** Format: int64 */
            startXp: number | null;
            /** Format: int64 */
            endXp: number | null;
            /** Format: int64 */
            gainedXp: number;
            /** Format: int16 */
            startLevel: number | null;
            /** Format: int16 */
            endLevel: number | null;
            /** Format: int32 */
            gainedLevels: number;
        };
        SkillSample: {
            /** Format: date-time */
            capturedAt: string;
            /** Format: int16 */
            skill: number;
            /** Format: int32 */
            rank: number | null;
            /** Format: int16 */
            level: number | null;
            /** Format: int64 */
            xp: number | null;
        };
        SpreadScan: {
            /** Format: double */
            taxRate: number;
            /** Format: int64 */
            taxCapPerItem: number;
            exemptionsResolved: boolean;
            candidates: components["schemas"]["MarginCandidate"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    SearchItems: {
        parameters: {
            query?: {
                search?: string;
                members?: boolean;
                minBuyLimit?: number;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfItemSummary"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Not Modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetItemPrices: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                interval?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPriceSeries"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetItemStats: {
        parameters: {
            query?: {
                window?: string;
                interval?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemStats"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetMovers: {
        parameters: {
            query?: {
                window?: string;
                interval?: string;
                minVolume?: number;
                minPrice?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoversResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetSpreads: {
        parameters: {
            query?: {
                minVolume?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpreadScan"];
                };
            };
        };
    };
    GetIngestStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestStatusResponse"];
                };
            };
        };
    };
    GetIngestCoverage: {
        parameters: {
            query?: {
                interval?: string;
                window?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageReport"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateAlert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAlertRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetPlayerHistory: {
        parameters: {
            query?: {
                skill?: number;
                from?: string;
                limit?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerHistoryResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetPlayerGains: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerGainsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    TrackPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
